# Define these variables in group_vars/staging/vault.yml

mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_readonly_password: "{{ vault_mysql_readonly_password }}"
redis_password: "{{ vault_redis_password }}"
