# Define accompanying passwords/secrets in group_vars/production/vault.yml
laravel_apps:
  example.com:
    site_hosts:
      - canonical: example.com
        redirects:
          - www.example.com
    local_path: ../laravel # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:example/example.git # replace with your Git repo URL
    repo_subtree_path: laravel # relative path to your Bedrock/WP directory in your repo
    branch: master
    ssl:
      enabled: false 
      provider: letsencrypt
    cache:
      enabled: false
